stages:
  - build
  - publish

variables:
  REGISTRY: hub.alterway.fr

before_script:
  - if [[ "$CI_BUILD_REF_NAME" != master ]]; then REGISTRY="$REGISTRY/$CI_BUILD_REF_NAME"; fi
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY/mysql:5.7 5.7/
    - docker build --pull -t $REGISTRY/mysql:5.6 5.6/
    - docker build --pull -t $REGISTRY/mysql:5.5 5.5/
    - docker push $REGISTRY/mysql:5.7
    - docker push $REGISTRY/mysql:5.6
    - docker push $REGISTRY/mysql:5.5
  only:
    - preprod
    - master

publish:
  stage: publish
  script:
    - docker pull -q $REGISTRY/mysql:5.5
    - docker tag $REGISTRY/mysql:5.5 $CI_REGISTRY_IMAGE:5.5
    - docker push $CI_REGISTRY_IMAGE:5.5
   
    - docker pull -q $REGISTRY/mysql:5.6
    - docker tag $REGISTRY/mysql:5.6 $CI_REGISTRY_IMAGE:5.6
    - docker push  $CI_REGISTRY_IMAGE:5.6

    - docker pull -q $REGISTRY/mysql:5.7
    - docker tag $REGISTRY/mysql:5.7 $CI_REGISTRY_IMAGE:5.7
    - docker push  $CI_REGISTRY_IMAGE:5.7

  only:
    - master
